# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-17 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangagerbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.BooleanField(default=True, verbose_name='出版状态，0未出版，1出版'),
        ),
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='作者联系方式'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=32, verbose_name='图书名'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_add',
            field=models.DateTimeField(verbose_name='上架日期'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publish_year',
            field=models.DateField(verbose_name='出版日期'),
        ),
        migrations.AlterField(
            model_name='book',
            name='stocks',
            field=models.IntegerField(verbose_name='图书库存'),
        ),
    ]
